/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as StrukturRouteImport } from './routes/struktur'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KolaborasiRouteImport } from './routes/kolaborasi'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const StrukturRoute = StrukturRouteImport.update({
  id: '/struktur',
  path: '/struktur',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaborasiRoute = KolaborasiRouteImport.update({
  id: '/kolaborasi',
  path: '/kolaborasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/program': typeof ProgramRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/kolaborasi'
    | '/kontak'
    | '/program'
    | '/struktur'
    | '/tentang-kami'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/kolaborasi'
    | '/kontak'
    | '/program'
    | '/struktur'
    | '/tentang-kami'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/kolaborasi'
    | '/kontak'
    | '/program'
    | '/struktur'
    | '/tentang-kami'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  KolaborasiRoute: typeof KolaborasiRoute
  KontakRoute: typeof KontakRoute
  ProgramRoute: typeof ProgramRoute
  StrukturRoute: typeof StrukturRoute
  TentangKamiRoute: typeof TentangKamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/struktur': {
      id: '/struktur'
      path: '/struktur'
      fullPath: '/struktur'
      preLoaderRoute: typeof StrukturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolaborasi': {
      id: '/kolaborasi'
      path: '/kolaborasi'
      fullPath: '/kolaborasi'
      preLoaderRoute: typeof KolaborasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  KolaborasiRoute: KolaborasiRoute,
  KontakRoute: KontakRoute,
  ProgramRoute: ProgramRoute,
  StrukturRoute: StrukturRoute,
  TentangKamiRoute: TentangKamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
