/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as StrukturRouteImport } from './routes/struktur'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KolaborasiRouteImport } from './routes/kolaborasi'
import { Route as GabungRouteImport } from './routes/gabung'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramIndexRouteImport } from './routes/program/_index'
import { Route as GaleriIndexRouteImport } from './routes/galeri/_index'
import { Route as BeritaIndexRouteImport } from './routes/berita/_index'
import { Route as ProgramIdDetailRouteImport } from './routes/program/$id/detail'
import { Route as GaleriIdDetailRouteImport } from './routes/galeri/$id/detail'
import { Route as BeritaSlugDetailRouteImport } from './routes/berita/$slug/detail'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const StrukturRoute = StrukturRouteImport.update({
  id: '/struktur',
  path: '/struktur',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KolaborasiRoute = KolaborasiRouteImport.update({
  id: '/kolaborasi',
  path: '/kolaborasi',
  getParentRoute: () => rootRouteImport,
} as any)
const GabungRoute = GabungRouteImport.update({
  id: '/gabung',
  path: '/gabung',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/program/_index',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriIndexRoute = GaleriIndexRouteImport.update({
  id: '/galeri/_index',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/_index',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIdDetailRoute = ProgramIdDetailRouteImport.update({
  id: '/program/$id/detail',
  path: '/program/$id/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriIdDetailRoute = GaleriIdDetailRouteImport.update({
  id: '/galeri/$id/detail',
  path: '/galeri/$id/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugDetailRoute = BeritaSlugDetailRouteImport.update({
  id: '/berita/$slug/detail',
  path: '/berita/$slug/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gabung': typeof GabungRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/berita': typeof BeritaIndexRoute
  '/galeri': typeof GaleriIndexRoute
  '/program': typeof ProgramIndexRoute
  '/berita/$slug/detail': typeof BeritaSlugDetailRoute
  '/galeri/$id/detail': typeof GaleriIdDetailRoute
  '/program/$id/detail': typeof ProgramIdDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gabung': typeof GabungRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/berita': typeof BeritaIndexRoute
  '/galeri': typeof GaleriIndexRoute
  '/program': typeof ProgramIndexRoute
  '/berita/$slug/detail': typeof BeritaSlugDetailRoute
  '/galeri/$id/detail': typeof GaleriIdDetailRoute
  '/program/$id/detail': typeof ProgramIdDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gabung': typeof GabungRoute
  '/kolaborasi': typeof KolaborasiRoute
  '/kontak': typeof KontakRoute
  '/struktur': typeof StrukturRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/berita/_index': typeof BeritaIndexRoute
  '/galeri/_index': typeof GaleriIndexRoute
  '/program/_index': typeof ProgramIndexRoute
  '/berita/$slug/detail': typeof BeritaSlugDetailRoute
  '/galeri/$id/detail': typeof GaleriIdDetailRoute
  '/program/$id/detail': typeof ProgramIdDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gabung'
    | '/kolaborasi'
    | '/kontak'
    | '/struktur'
    | '/tentang-kami'
    | '/berita'
    | '/galeri'
    | '/program'
    | '/berita/$slug/detail'
    | '/galeri/$id/detail'
    | '/program/$id/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gabung'
    | '/kolaborasi'
    | '/kontak'
    | '/struktur'
    | '/tentang-kami'
    | '/berita'
    | '/galeri'
    | '/program'
    | '/berita/$slug/detail'
    | '/galeri/$id/detail'
    | '/program/$id/detail'
  id:
    | '__root__'
    | '/'
    | '/gabung'
    | '/kolaborasi'
    | '/kontak'
    | '/struktur'
    | '/tentang-kami'
    | '/berita/_index'
    | '/galeri/_index'
    | '/program/_index'
    | '/berita/$slug/detail'
    | '/galeri/$id/detail'
    | '/program/$id/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GabungRoute: typeof GabungRoute
  KolaborasiRoute: typeof KolaborasiRoute
  KontakRoute: typeof KontakRoute
  StrukturRoute: typeof StrukturRoute
  TentangKamiRoute: typeof TentangKamiRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  GaleriIndexRoute: typeof GaleriIndexRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
  BeritaSlugDetailRoute: typeof BeritaSlugDetailRoute
  GaleriIdDetailRoute: typeof GaleriIdDetailRoute
  ProgramIdDetailRoute: typeof ProgramIdDetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/struktur': {
      id: '/struktur'
      path: '/struktur'
      fullPath: '/struktur'
      preLoaderRoute: typeof StrukturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kolaborasi': {
      id: '/kolaborasi'
      path: '/kolaborasi'
      fullPath: '/kolaborasi'
      preLoaderRoute: typeof KolaborasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gabung': {
      id: '/gabung'
      path: '/gabung'
      fullPath: '/gabung'
      preLoaderRoute: typeof GabungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/_index': {
      id: '/program/_index'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri/_index': {
      id: '/galeri/_index'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/_index': {
      id: '/berita/_index'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$id/detail': {
      id: '/program/$id/detail'
      path: '/program/$id/detail'
      fullPath: '/program/$id/detail'
      preLoaderRoute: typeof ProgramIdDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri/$id/detail': {
      id: '/galeri/$id/detail'
      path: '/galeri/$id/detail'
      fullPath: '/galeri/$id/detail'
      preLoaderRoute: typeof GaleriIdDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug/detail': {
      id: '/berita/$slug/detail'
      path: '/berita/$slug/detail'
      fullPath: '/berita/$slug/detail'
      preLoaderRoute: typeof BeritaSlugDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GabungRoute: GabungRoute,
  KolaborasiRoute: KolaborasiRoute,
  KontakRoute: KontakRoute,
  StrukturRoute: StrukturRoute,
  TentangKamiRoute: TentangKamiRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  GaleriIndexRoute: GaleriIndexRoute,
  ProgramIndexRoute: ProgramIndexRoute,
  BeritaSlugDetailRoute: BeritaSlugDetailRoute,
  GaleriIdDetailRoute: GaleriIdDetailRoute,
  ProgramIdDetailRoute: ProgramIdDetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
