/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appmenuIndexRouteImport } from './routes/(app)/(menu)/index'
import { Route as apppublicationProgramRouteImport } from './routes/(app)/(publication)/program'
import { Route as apppublicationKategoriRouteImport } from './routes/(app)/(publication)/kategori'
import { Route as apppartnershipKolaborasiRouteImport } from './routes/(app)/(partnership)/kolaborasi'
import { Route as apporganizationPeriodeRouteImport } from './routes/(app)/(organization)/periode'
import { Route as apporganizationJabatanRouteImport } from './routes/(app)/(organization)/jabatan'
import { Route as apporganizationAnggotaRouteImport } from './routes/(app)/(organization)/anggota'
import { Route as apppublicationGaleriNewRouteImport } from './routes/(app)/(publication)/galeri/new'
import { Route as apppublicationGaleriIndexRouteImport } from './routes/(app)/(publication)/galeri/_index'
import { Route as apppublicationBeritaNewRouteImport } from './routes/(app)/(publication)/berita/new'
import { Route as apppublicationBeritaIndexRouteImport } from './routes/(app)/(publication)/berita/_index'
import { Route as apppublicationGaleriIdEditRouteImport } from './routes/(app)/(publication)/galeri/$id/edit'
import { Route as apppublicationGaleriIdDetailRouteImport } from './routes/(app)/(publication)/galeri/$id/detail'
import { Route as apppublicationBeritaSlugEditRouteImport } from './routes/(app)/(publication)/berita/$slug/edit'
import { Route as apppublicationBeritaSlugDetailRouteImport } from './routes/(app)/(publication)/berita/$slug/detail'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appmenuIndexRoute = appmenuIndexRouteImport.update({
  id: '/(menu)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const apppublicationProgramRoute = apppublicationProgramRouteImport.update({
  id: '/(publication)/program',
  path: '/program',
  getParentRoute: () => appRouteRoute,
} as any)
const apppublicationKategoriRoute = apppublicationKategoriRouteImport.update({
  id: '/(publication)/kategori',
  path: '/kategori',
  getParentRoute: () => appRouteRoute,
} as any)
const apppartnershipKolaborasiRoute =
  apppartnershipKolaborasiRouteImport.update({
    id: '/(partnership)/kolaborasi',
    path: '/kolaborasi',
    getParentRoute: () => appRouteRoute,
  } as any)
const apporganizationPeriodeRoute = apporganizationPeriodeRouteImport.update({
  id: '/(organization)/periode',
  path: '/periode',
  getParentRoute: () => appRouteRoute,
} as any)
const apporganizationJabatanRoute = apporganizationJabatanRouteImport.update({
  id: '/(organization)/jabatan',
  path: '/jabatan',
  getParentRoute: () => appRouteRoute,
} as any)
const apporganizationAnggotaRoute = apporganizationAnggotaRouteImport.update({
  id: '/(organization)/anggota',
  path: '/anggota',
  getParentRoute: () => appRouteRoute,
} as any)
const apppublicationGaleriNewRoute = apppublicationGaleriNewRouteImport.update({
  id: '/(publication)/galeri/new',
  path: '/galeri/new',
  getParentRoute: () => appRouteRoute,
} as any)
const apppublicationGaleriIndexRoute =
  apppublicationGaleriIndexRouteImport.update({
    id: '/(publication)/galeri/_index',
    path: '/galeri',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppublicationBeritaNewRoute = apppublicationBeritaNewRouteImport.update({
  id: '/(publication)/berita/new',
  path: '/berita/new',
  getParentRoute: () => appRouteRoute,
} as any)
const apppublicationBeritaIndexRoute =
  apppublicationBeritaIndexRouteImport.update({
    id: '/(publication)/berita/_index',
    path: '/berita',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppublicationGaleriIdEditRoute =
  apppublicationGaleriIdEditRouteImport.update({
    id: '/(publication)/galeri/$id/edit',
    path: '/galeri/$id/edit',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppublicationGaleriIdDetailRoute =
  apppublicationGaleriIdDetailRouteImport.update({
    id: '/(publication)/galeri/$id/detail',
    path: '/galeri/$id/detail',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppublicationBeritaSlugEditRoute =
  apppublicationBeritaSlugEditRouteImport.update({
    id: '/(publication)/berita/$slug/edit',
    path: '/berita/$slug/edit',
    getParentRoute: () => appRouteRoute,
  } as any)
const apppublicationBeritaSlugDetailRoute =
  apppublicationBeritaSlugDetailRouteImport.update({
    id: '/(publication)/berita/$slug/detail',
    path: '/berita/$slug/detail',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/anggota': typeof apporganizationAnggotaRoute
  '/jabatan': typeof apporganizationJabatanRoute
  '/periode': typeof apporganizationPeriodeRoute
  '/kolaborasi': typeof apppartnershipKolaborasiRoute
  '/kategori': typeof apppublicationKategoriRoute
  '/program': typeof apppublicationProgramRoute
  '/': typeof appmenuIndexRoute
  '/berita': typeof apppublicationBeritaIndexRoute
  '/berita/new': typeof apppublicationBeritaNewRoute
  '/galeri': typeof apppublicationGaleriIndexRoute
  '/galeri/new': typeof apppublicationGaleriNewRoute
  '/berita/$slug/detail': typeof apppublicationBeritaSlugDetailRoute
  '/berita/$slug/edit': typeof apppublicationBeritaSlugEditRoute
  '/galeri/$id/detail': typeof apppublicationGaleriIdDetailRoute
  '/galeri/$id/edit': typeof apppublicationGaleriIdEditRoute
}
export interface FileRoutesByTo {
  '/anggota': typeof apporganizationAnggotaRoute
  '/jabatan': typeof apporganizationJabatanRoute
  '/periode': typeof apporganizationPeriodeRoute
  '/kolaborasi': typeof apppartnershipKolaborasiRoute
  '/kategori': typeof apppublicationKategoriRoute
  '/program': typeof apppublicationProgramRoute
  '/': typeof appmenuIndexRoute
  '/berita': typeof apppublicationBeritaIndexRoute
  '/berita/new': typeof apppublicationBeritaNewRoute
  '/galeri': typeof apppublicationGaleriIndexRoute
  '/galeri/new': typeof apppublicationGaleriNewRoute
  '/berita/$slug/detail': typeof apppublicationBeritaSlugDetailRoute
  '/berita/$slug/edit': typeof apppublicationBeritaSlugEditRoute
  '/galeri/$id/detail': typeof apppublicationGaleriIdDetailRoute
  '/galeri/$id/edit': typeof apppublicationGaleriIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/(organization)/anggota': typeof apporganizationAnggotaRoute
  '/(app)/(organization)/jabatan': typeof apporganizationJabatanRoute
  '/(app)/(organization)/periode': typeof apporganizationPeriodeRoute
  '/(app)/(partnership)/kolaborasi': typeof apppartnershipKolaborasiRoute
  '/(app)/(publication)/kategori': typeof apppublicationKategoriRoute
  '/(app)/(publication)/program': typeof apppublicationProgramRoute
  '/(app)/(menu)/': typeof appmenuIndexRoute
  '/(app)/(publication)/berita/_index': typeof apppublicationBeritaIndexRoute
  '/(app)/(publication)/berita/new': typeof apppublicationBeritaNewRoute
  '/(app)/(publication)/galeri/_index': typeof apppublicationGaleriIndexRoute
  '/(app)/(publication)/galeri/new': typeof apppublicationGaleriNewRoute
  '/(app)/(publication)/berita/$slug/detail': typeof apppublicationBeritaSlugDetailRoute
  '/(app)/(publication)/berita/$slug/edit': typeof apppublicationBeritaSlugEditRoute
  '/(app)/(publication)/galeri/$id/detail': typeof apppublicationGaleriIdDetailRoute
  '/(app)/(publication)/galeri/$id/edit': typeof apppublicationGaleriIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/anggota'
    | '/jabatan'
    | '/periode'
    | '/kolaborasi'
    | '/kategori'
    | '/program'
    | '/'
    | '/berita'
    | '/berita/new'
    | '/galeri'
    | '/galeri/new'
    | '/berita/$slug/detail'
    | '/berita/$slug/edit'
    | '/galeri/$id/detail'
    | '/galeri/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/anggota'
    | '/jabatan'
    | '/periode'
    | '/kolaborasi'
    | '/kategori'
    | '/program'
    | '/'
    | '/berita'
    | '/berita/new'
    | '/galeri'
    | '/galeri/new'
    | '/berita/$slug/detail'
    | '/berita/$slug/edit'
    | '/galeri/$id/detail'
    | '/galeri/$id/edit'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/(organization)/anggota'
    | '/(app)/(organization)/jabatan'
    | '/(app)/(organization)/periode'
    | '/(app)/(partnership)/kolaborasi'
    | '/(app)/(publication)/kategori'
    | '/(app)/(publication)/program'
    | '/(app)/(menu)/'
    | '/(app)/(publication)/berita/_index'
    | '/(app)/(publication)/berita/new'
    | '/(app)/(publication)/galeri/_index'
    | '/(app)/(publication)/galeri/new'
    | '/(app)/(publication)/berita/$slug/detail'
    | '/(app)/(publication)/berita/$slug/edit'
    | '/(app)/(publication)/galeri/$id/detail'
    | '/(app)/(publication)/galeri/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(menu)/': {
      id: '/(app)/(menu)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appmenuIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/program': {
      id: '/(app)/(publication)/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof apppublicationProgramRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/kategori': {
      id: '/(app)/(publication)/kategori'
      path: '/kategori'
      fullPath: '/kategori'
      preLoaderRoute: typeof apppublicationKategoriRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(partnership)/kolaborasi': {
      id: '/(app)/(partnership)/kolaborasi'
      path: '/kolaborasi'
      fullPath: '/kolaborasi'
      preLoaderRoute: typeof apppartnershipKolaborasiRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/periode': {
      id: '/(app)/(organization)/periode'
      path: '/periode'
      fullPath: '/periode'
      preLoaderRoute: typeof apporganizationPeriodeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/jabatan': {
      id: '/(app)/(organization)/jabatan'
      path: '/jabatan'
      fullPath: '/jabatan'
      preLoaderRoute: typeof apporganizationJabatanRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/anggota': {
      id: '/(app)/(organization)/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof apporganizationAnggotaRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/galeri/new': {
      id: '/(app)/(publication)/galeri/new'
      path: '/galeri/new'
      fullPath: '/galeri/new'
      preLoaderRoute: typeof apppublicationGaleriNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/galeri/_index': {
      id: '/(app)/(publication)/galeri/_index'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof apppublicationGaleriIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/berita/new': {
      id: '/(app)/(publication)/berita/new'
      path: '/berita/new'
      fullPath: '/berita/new'
      preLoaderRoute: typeof apppublicationBeritaNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/berita/_index': {
      id: '/(app)/(publication)/berita/_index'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof apppublicationBeritaIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/galeri/$id/edit': {
      id: '/(app)/(publication)/galeri/$id/edit'
      path: '/galeri/$id/edit'
      fullPath: '/galeri/$id/edit'
      preLoaderRoute: typeof apppublicationGaleriIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/galeri/$id/detail': {
      id: '/(app)/(publication)/galeri/$id/detail'
      path: '/galeri/$id/detail'
      fullPath: '/galeri/$id/detail'
      preLoaderRoute: typeof apppublicationGaleriIdDetailRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/berita/$slug/edit': {
      id: '/(app)/(publication)/berita/$slug/edit'
      path: '/berita/$slug/edit'
      fullPath: '/berita/$slug/edit'
      preLoaderRoute: typeof apppublicationBeritaSlugEditRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(publication)/berita/$slug/detail': {
      id: '/(app)/(publication)/berita/$slug/detail'
      path: '/berita/$slug/detail'
      fullPath: '/berita/$slug/detail'
      preLoaderRoute: typeof apppublicationBeritaSlugDetailRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  apporganizationAnggotaRoute: typeof apporganizationAnggotaRoute
  apporganizationJabatanRoute: typeof apporganizationJabatanRoute
  apporganizationPeriodeRoute: typeof apporganizationPeriodeRoute
  apppartnershipKolaborasiRoute: typeof apppartnershipKolaborasiRoute
  apppublicationKategoriRoute: typeof apppublicationKategoriRoute
  apppublicationProgramRoute: typeof apppublicationProgramRoute
  appmenuIndexRoute: typeof appmenuIndexRoute
  apppublicationBeritaIndexRoute: typeof apppublicationBeritaIndexRoute
  apppublicationBeritaNewRoute: typeof apppublicationBeritaNewRoute
  apppublicationGaleriIndexRoute: typeof apppublicationGaleriIndexRoute
  apppublicationGaleriNewRoute: typeof apppublicationGaleriNewRoute
  apppublicationBeritaSlugDetailRoute: typeof apppublicationBeritaSlugDetailRoute
  apppublicationBeritaSlugEditRoute: typeof apppublicationBeritaSlugEditRoute
  apppublicationGaleriIdDetailRoute: typeof apppublicationGaleriIdDetailRoute
  apppublicationGaleriIdEditRoute: typeof apppublicationGaleriIdEditRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  apporganizationAnggotaRoute: apporganizationAnggotaRoute,
  apporganizationJabatanRoute: apporganizationJabatanRoute,
  apporganizationPeriodeRoute: apporganizationPeriodeRoute,
  apppartnershipKolaborasiRoute: apppartnershipKolaborasiRoute,
  apppublicationKategoriRoute: apppublicationKategoriRoute,
  apppublicationProgramRoute: apppublicationProgramRoute,
  appmenuIndexRoute: appmenuIndexRoute,
  apppublicationBeritaIndexRoute: apppublicationBeritaIndexRoute,
  apppublicationBeritaNewRoute: apppublicationBeritaNewRoute,
  apppublicationGaleriIndexRoute: apppublicationGaleriIndexRoute,
  apppublicationGaleriNewRoute: apppublicationGaleriNewRoute,
  apppublicationBeritaSlugDetailRoute: apppublicationBeritaSlugDetailRoute,
  apppublicationBeritaSlugEditRoute: apppublicationBeritaSlugEditRoute,
  apppublicationGaleriIdDetailRoute: apppublicationGaleriIdDetailRoute,
  apppublicationGaleriIdEditRoute: apppublicationGaleriIdEditRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
