/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appmenuIndexRouteImport } from './routes/(app)/(menu)/index'
import { Route as apporganizationPeriodeRouteImport } from './routes/(app)/(organization)/periode'
import { Route as apporganizationJabatanRouteImport } from './routes/(app)/(organization)/jabatan'
import { Route as apporganizationAnggotaRouteImport } from './routes/(app)/(organization)/anggota'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appmenuIndexRoute = appmenuIndexRouteImport.update({
  id: '/(menu)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const apporganizationPeriodeRoute = apporganizationPeriodeRouteImport.update({
  id: '/(organization)/periode',
  path: '/periode',
  getParentRoute: () => appRouteRoute,
} as any)
const apporganizationJabatanRoute = apporganizationJabatanRouteImport.update({
  id: '/(organization)/jabatan',
  path: '/jabatan',
  getParentRoute: () => appRouteRoute,
} as any)
const apporganizationAnggotaRoute = apporganizationAnggotaRouteImport.update({
  id: '/(organization)/anggota',
  path: '/anggota',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/anggota': typeof apporganizationAnggotaRoute
  '/jabatan': typeof apporganizationJabatanRoute
  '/periode': typeof apporganizationPeriodeRoute
  '/': typeof appmenuIndexRoute
}
export interface FileRoutesByTo {
  '/anggota': typeof apporganizationAnggotaRoute
  '/jabatan': typeof apporganizationJabatanRoute
  '/periode': typeof apporganizationPeriodeRoute
  '/': typeof appmenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/(organization)/anggota': typeof apporganizationAnggotaRoute
  '/(app)/(organization)/jabatan': typeof apporganizationJabatanRoute
  '/(app)/(organization)/periode': typeof apporganizationPeriodeRoute
  '/(app)/(menu)/': typeof appmenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/anggota' | '/jabatan' | '/periode' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/anggota' | '/jabatan' | '/periode' | '/'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/(organization)/anggota'
    | '/(app)/(organization)/jabatan'
    | '/(app)/(organization)/periode'
    | '/(app)/(menu)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(menu)/': {
      id: '/(app)/(menu)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appmenuIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/periode': {
      id: '/(app)/(organization)/periode'
      path: '/periode'
      fullPath: '/periode'
      preLoaderRoute: typeof apporganizationPeriodeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/jabatan': {
      id: '/(app)/(organization)/jabatan'
      path: '/jabatan'
      fullPath: '/jabatan'
      preLoaderRoute: typeof apporganizationJabatanRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(organization)/anggota': {
      id: '/(app)/(organization)/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof apporganizationAnggotaRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  apporganizationAnggotaRoute: typeof apporganizationAnggotaRoute
  apporganizationJabatanRoute: typeof apporganizationJabatanRoute
  apporganizationPeriodeRoute: typeof apporganizationPeriodeRoute
  appmenuIndexRoute: typeof appmenuIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  apporganizationAnggotaRoute: apporganizationAnggotaRoute,
  apporganizationJabatanRoute: apporganizationJabatanRoute,
  apporganizationPeriodeRoute: apporganizationPeriodeRoute,
  appmenuIndexRoute: appmenuIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
