/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appmenuIndexRouteImport } from './routes/(app)/(menu)/index'
import { Route as appmenuStrukturRouteImport } from './routes/(app)/(menu)/struktur'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appmenuIndexRoute = appmenuIndexRouteImport.update({
  id: '/(menu)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appmenuStrukturRoute = appmenuStrukturRouteImport.update({
  id: '/(menu)/struktur',
  path: '/struktur',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/struktur': typeof appmenuStrukturRoute
  '/': typeof appmenuIndexRoute
}
export interface FileRoutesByTo {
  '/struktur': typeof appmenuStrukturRoute
  '/': typeof appmenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/(menu)/struktur': typeof appmenuStrukturRoute
  '/(app)/(menu)/': typeof appmenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/struktur' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/struktur' | '/'
  id: '__root__' | '/(app)' | '/(app)/(menu)/struktur' | '/(app)/(menu)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(menu)/': {
      id: '/(app)/(menu)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appmenuIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(menu)/struktur': {
      id: '/(app)/(menu)/struktur'
      path: '/struktur'
      fullPath: '/struktur'
      preLoaderRoute: typeof appmenuStrukturRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appmenuStrukturRoute: typeof appmenuStrukturRoute
  appmenuIndexRoute: typeof appmenuIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appmenuStrukturRoute: appmenuStrukturRoute,
  appmenuIndexRoute: appmenuIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
